export const PLAYLIST_DATA = [
  {
    id: 1,
    title: "Sahte",
    artist: "Hande Yener",
    duration: "3:45",
    active: true,
    file: "/assets/music/hande_yener_sahte.mp3",
  },
  {
    id: 2,
    title: "Oyun Bitti",
    artist: "Sertab Erener",
    duration: "4:21",
    active: false,
    file: "/assets/music/sertab_erener_oyun_bitti.mp3",
  },
  {
    id: 3,
    title: "Intikam",
    artist: "Demet Akalin",
    duration: "4:21",
    active: false,
    file: "/assets/music/demet_akalin_intikam.mp3",
  },
  {
    id: 4,
    title: "Hardadir",
    artist: "Qaraqan",
    duration: "4:21",
    active: false,
    file: "/assets/music/qaraqan_hardadir.mp3",
  },
  {
    id: 5,
    title: "Talking in your sleep",
    artist: "The Romantics",
    duration: "4:21",
    active: false,
    file: "/assets/music/talking_in_your_sleep_the_romantics.mp3",
  },
  {
    id: 6,
    title: "Virtual World",
    artist: "Fibre",
    duration: "4:21",
    active: false,
    file: "/assets/music/virtual_world_fibre.mp3",
  },
];
